export const questionsData = {
   "learnQuestions": [
   {"id": 1, "question": "Is the font Monsterrat with or without ms ?", "score": 0.5},
    {"id": 2, "question": "Is the font Helvetica with or without ms ?", "score": 0.5},
    {"id": 3, "question": "Is the font Roboto with or without ms ?", "score": 0.5},
    {"id": 4, "question": "Is the font Open Sans with or without ms ?", "score": 0.5},
    {"id": 5, "question": "Is the font Comic sans ms with or without ms ?", "score": 0.5},
    {"id": 6, "question": "Is the font Arial with or without ms ?", "score": 0.5},
    {"id": 7, "question": "Is the font Times New Roman with or without ms ?", "score": 0.5},
    {"id": 8, "question": "Is Lacoste logo a mascot logo or an abstract ?", "score": 1},
    {"id": 9, "question": "Is Uber a wordmark logo or an abstract logo ?", "score": 1},
    {"id": 10, "question": "Give 5 environment friendly brands names", "score": 2},
    {"id": 11, "question": "Are with serif typographies serious or fun use typographies ?", "score": 2},
    {"id": 12, "question": "What’s the difference between RGB and CMYK colors ?", "score": 2},
    {"id": 13, "question": "Which brand powerd collective perception of Santa Claud in red since 1964 ?", "score": 0.5},
    {"id": 14, "question": "Which kids toys brand had huge success in 2023 after the cinematographique adaptation of one of their bestseller product ?", "score": 2},
    {"id": 15, "question": "Which fast-food brand is known for their their fun and accurate communication agency on social media ?", "score": 0.5},
    {"id": 16, "question": "Is the logo Ferrari an emblem logo or a monogram logo ?", "score": 1},
    {"id": 17, "question": "What was the main color of McDonald’s their 2009 rebranding ?", "score": 0.5},
    ],

   "challengeQuestions": [
    {"id": 18, "question": "Create your logo in 1 min", "success": "Move 2 squares forward", "fail": "Pass your turn next challenge"},
    {"id": 19, "question": "Create your palette in 30 sec", "success": "Move 2 squares forward", "fail": "You pass your turn next challenge"},
    {"id": 20, "question": "Determine your moodboard in 45 sec", "success": "You can choose the feature the player of your choice loses", "fail": "You lose all your features"},
    {"id": 21, "question": "Determine your moodboard in 45 sec", "success": "Move 2 squares forward", "fail": "Move 2 squares backward"},
    {"id": 22, "question": "Determine your moodboard in 45 sec ( you can use your phone )", "success": "Move 2 squares forward", "fail": "Move 2 squares backward"},
    {"id": 23, "question": "Select your typography in 30 sec", "success": "Move 2 squares forward", "fail": "Next challenge you pass your turn"},
    {"id": 24, "question": "Create your logo in 1 min", "success": "Choose a team/player that will lose their logo", "fail": "Nothing happens"},
    {"id": 25, "question": "Determine your motto in 30 sec", "success": "Choose a player who loses his/her motto", "fail": "Go back to the start line"},
    {"id": 26, "question": "Select your typography in 30 sec", "success": "You can choose a feature another player will lose", "fail": "You lose all your features"},
    {"id": 27, "question": "Determine your moodboard in 45 sec", "success": "Move 2 squares forward", "fail": "Next challenge you pass your turn"},
    {"id": 28, "question": "Determine your motto in 30 sec", "success": "Move 2 squares forward", "fail": "Move 2 squares backward"},
    {"id": 29, "question": "Find your brand name in 15 sec", "success": "Move 1 square forward", "fail": "Move 2 squares backward"},
    {"id": 30, "question": "Determine your motto in 30 sec", "success": "Move 2 squares forward", "fail": "Move 2 squares backward"},
    {"id": 31, "question": "Determine your moodboard in 45 sec", "success": "Roll dices and move your pawn forward according to the result displayed", "fail": "Roll dices and move your pawn backward according to the result displayed"},
    {"id": 32, "question": "Select your typography in 30 sec", "success": "Roll dices and move your pawn forward according to the result displayed", "fail": "Roll dices and move your pawn backward according to the result displayed"},
    {"id": 33, "question": "Create your logo in 1 min", "success": "You can keep this card in the case you lose one of your features", "fail": "You must give the feature the player on your right want to him/her"},
    {"id": 34, "question": "Create your palette in 30 sec", "success": "The player of your choice loses the feature you want", "fail": "Your opponent chose the feature of their choice"},
    {"id": 35, "question": "Create your brand name in 15 sec", "success": "Move 1 squares forward", "fail": "Move 2 squares backward"},
    {"id": 36, "question": "Select your typography in 30 sec", "success": "Keep this card in case you might lose a feature", "fail": "Nothing happens"},
    {"id": 37, "question": "Create your palette in 30 sec", "success": "You can choose the feature you want next challenge", "fail": "Move 2 squares backward"},
    {"id": 38, "question": "Create your palette in 30 sec", "success": "Steal 1 color from anotherplayer’s palette", "fail": "Another player choose 1 of your colors"},
    {"id": 39, "question": "Select your typography in 30 sec", "success": "Keep this card as protection if you lose a feature later", "fail": "The group assigns you a random typography"},
    {"id": 40, "question": "Draw your logo in 30 sec", "success": "Move 1 square forward", "fail": "Move 3 squares backward"},
    {"id": 41, "question": "Find a slogan in 20 sec", "success": "Choose 1 player who will move 1 square backward", "fail": "Move 1 square backward"}
   ]
}